#define PUNTO_Y_COMA ";"
#define ELEMENTO_NO_ENCONTRADO "\"Elemento no encontrado\""
#define LISTA_VACIA "\"Lista vacia\""
#define VALOR_NO_DETERMINADO "_valorNoDeterminado"
#define CONST_INT "CONST_INT"
#define CONST_STR "CONST_STR"
#define WRITE_NODE "WRITE"
#define READ_NODE "READ"
#define IF "IF"
#define NOMBRE_ARCHIVO_INTERMEDIA_TXT "intermedia.txt"
#define TIPO_INT "INT"
#define TIPO_FLOAT "FLOAT"
#define TIPO_STRING "STRING"
#define RESULTADO "@resultado"